StephenZeng.MvcTemplate.Web/Controllers/UsersAdminController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using StephenZeng.MvcTemplate.Common.Entities;
using StephenZeng.MvcTemplate.Web.Helpers;
using StephenZeng.MvcTemplate.Web.Models;
using StephenZeng.MvcTemplate.Web.Services;

namespace StephenZeng.MvcTemplate.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : BaseController
    {
        private readonly IEmailService _emailService;

        public UsersAdminController(IEmailService emailService)
        {
            _emailService = emailService;
        }

        public async Task<ActionResult> Index(int? page)
        {
            var pageNumber = page ?? 1;

            var list = await UserManager.Users
                .OrderByDescending(u => u.RegisterTime)
                .Project().To<UserViewModel>()
                .ToPagedListAsync(pageNumber, PageSize);

            return View(list);
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = await UserManager.FindByIdAsync(id);
            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        public async Task<ActionResult> Create()
        {
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new User { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            var viewModel = Mapper.Map<EditUserViewModel>(user);
            viewModel.RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
            {
                Selected = userRoles.Contains(x.Name),
                Text = x.Name,
                Value = x.Name
            });

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                var needToSendApproveNotification = editUser.Approved && !user.Approved;

                user = Mapper.Map(editUser, user);

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }

                if (needToSendApproveNotification)
                {
                    var loginUrl = Url.Action("Login", "Account", new { }, protocol: Request.Url.Scheme);
                    var emailContent = string.Format(@"<p>Dear {0} {1},</p><p></p> 
                    <p>Your registration has been approved. Please login the system by clicking the link below , or copy it then open it in your browser.</p>
                    <p>{2}</p>
                    <p></p>
                    <p></p> 
                    <p>This message was sent by system. Please do not reply.</p>
                    <p>Mvc Template</p>", user.FirstName, user.LastName, loginUrl);

                    await _emailService.SendAsync("Mvc Template - Your registration has been approved", emailContent, user.Email);
                }

                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);

                if (user == null)
                {
                    return HttpNotFound();
                }

                if (await UserManager.IsInRoleAsync(id, "Admin"))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "You are not allowed to delete admin users");
                }
                
                var result = await UserManager.DeleteAsync(user);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

StephenZeng.MvcTemplate.Web/Views/UsersAdmin/Create.cshtml
@model StephenZeng.MvcTemplate.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

StephenZeng.MvcTemplate.Web/Views/UsersAdmin/Delete.cshtml
@model StephenZeng.MvcTemplate.Common.Entities.User

<h4 class="text-danger">Are you sure you want to delete this User?</h4>

<div>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Email)</dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>Email confirmed</dt>
        <dd>
            @Model.EmailConfirmed.ToIcon()
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Approved)</dt>
        <dd>
            @Model.Approved.ToIcon()
        </dd>
        @if (ViewBag.RoleNames.Contains("Client"))
        {
            <dt>@Html.DisplayNameFor(model => model.Accounts)</dt>
            <dd>
                @Html.DisplayFor(model => model.Accounts)
            </dd>
            <dt>@Html.DisplayNameFor(model => model.AdviserEmail)</dt>
            <dd>
                @Html.DisplayFor(model => model.AdviserEmail)
            </dd>
        }
        <dt>@Html.DisplayNameFor(model => model.Roles)</dt>
        <dd>
            @string.Join(", ", ViewBag.RoleNames)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.RegisterTime)</dt>
        <dd>
            @Html.DisplayFor(model => model.RegisterTime)
        </dd>
        <dt></dt>
        <dd class="margin-top-35">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            }
        </dd>
    </dl>
</div>

<p>
    @Url.GoBackTo("Go back to list", "Index")
</p>

StephenZeng.MvcTemplate.Web/Views/UsersAdmin/Details.cshtml
@using StephenZeng.MvcTemplate.Web.Helpers
@model StephenZeng.MvcTemplate.Common.Entities.User

<div>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Email)</dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>Email confirmed</dt>
        <dd>
            @Model.EmailConfirmed.ToIcon()
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Approved)</dt>
        <dd>
            @Model.Approved.ToIcon()
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Address)</dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Roles)</dt>
        <dd>
            @string.Join(", ", ViewBag.RoleNames)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.RegisterTime)</dt>
        <dd>
            @Html.DisplayFor(model => model.RegisterTime)
        </dd>
        <dt></dt>
        <dd class="margin-top-35">
            <div class="pull-left margin-right-15">@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @Class = "btn btn-default" })</div>
            <div class="pull-left">@Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @Class = "btn btn-danger" })</div>
        </dd>
    </dl>
</div>

<p>
   @Url.GoBackTo("Go back to list", "Index")
</p>

StephenZeng.MvcTemplate.Web/Views/UsersAdmin/Edit.cshtml
@using StephenZeng.MvcTemplate.Web.Helpers
@model StephenZeng.MvcTemplate.Web.Models.EditUserViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-4">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-4">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-4">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group ">
            <div class="col-md-offset-2 col-md-6">
                @Html.EditorFor(model => model.EmailConfirmed)
                @Html.LabelFor(model => model.EmailConfirmed)
            </div>
        </div>

        <div class="form-group ">
            <div class="col-md-offset-2 col-md-6">
                @Html.EditorFor(model => model.Approved)
                @Html.LabelFor(model => model.Approved)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Roles", new {@class = "control-label col-md-2"})
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new {@class = "control-label margin-right-15"})
                }
            </span>
        </div>

        <div class="form-group margin-top-35">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<p>
   @Url.GoBackTo("Go back to list", "Index")
</p>

StephenZeng.MvcTemplate.Web/Views/UsersAdmin/Index.cshtml
@using StephenZeng.MvcTemplate.Web.Helpers;
@using PagedList.Mvc
@model PagedList.IPagedList<StephenZeng.MvcTemplate.Web.Models.UserViewModel>

<table class="table table-striped">
    <tr>
        <th>
            Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            Confirmed
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Approved)
        </th>
        <th>
            Registered
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @item.EmailConfirmed.ToIcon()
            </td>
            <td>
                @item.Approved.ToIcon()
            </td>
            <td>
                @item.RegisterTime.ToShortDateString()
            </td>
            <td>
                <a href="@Url.Action("Details", new{item.Id})" class="pull-right">
                    <i class="fa fa-edit"></i> Details
                </a>
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))